logrotate: false
buildDiscarder:
  $class: !by-name Log Rotation
properties:
  !key:by-name Rebuild Settings:
    autoRebuild: false
    rebuildDisabled: false
  !key:by-name Throttle Concurrent Builds:
    throttleEnabled: false
    throttleOption: project
    maxConcurrentTotal: 0
    maxConcurrentPerNode: 0
disable: false
concurrentBuild: false
hasSlaveAffinity: true
label: master
hasCustomQuietPeriod: false
quiet_period: 5
hasCustomScmCheckoutRetryCount: false
scmCheckoutRetryCount: 0
blockBuildWhenUpstreamBuilding: false
blockBuildWhenDownstreamBuilding: false
hasCustomWorkspace: false
!key:by-name Poll SCM:
  scmpoll_spec: H * * * *
  ignorePostCommitHooks: false
builder:
  command: apt-get update

    apt-get install -y -qq --no-install-recommends make curl

    cd codiad && make && cd ..

    cd test

    curl -sL https://deb.nodesource.com/setup_0.12 | bash -

    apt-get update && apt-get install -y nodejs

    curl -L https://npmjs.com/install.sh | sh

    npm install -g mocha

    npm install expect.js webdriverio

    mocha *.spec.js

  $class: !shell
$class: !freestyle